name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Lua
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update -qq
          sudo apt install -yq --no-install-suggests --no-install-recommends lua5.1 liblua5.1-0-dev
      - name: Build playlist parser
        run: luac -v -s -o vkplay-linux.luac src/vkplay.lua
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: vkplay-linux.luac
          path: vkplay-linux.luac

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Lua
        run: |
          export HOMEBREW_NO_ENV_HINTS=1
          brew update -q
          brew install -q lua@5.1
      - name: Build playlist parser
        run: luac5.1 -v -s -o vkplay-macos.luac src/vkplay.lua
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: vkplay-macos.luac
          path: vkplay-macos.luac
  
#  build_windows:
#    name: Build playlist parser for Windows
#    runs-on: windows-latest
#    steps:
#      - uses actions/checkout@v3
#      - name: Install VLC
#        run: |
#          export DEBIAN_FRONTEND=noninteractive
#          sudo apt update -qq
#          sudo apt install -yq --no-install-suggests --no-install-recommends lua5.1 liblua5.1-0-dev
#      - name: Build playlist parser
#      - run: luac.exe -s -o vkplay.luac vkplay.lua
#      - name: Upload output file
#        uses: actions/upload-artifact@v3
#        with:
#          name: vkplay-windows.luac
#          path: vkplay-windows.luac
